version: "3"
services:
  springboot-app:
    container_name: filesystem-app
    image: filesystem-app
    build: .
    ports:
      - "9093:9093"
    depends_on:
      - postgresqldb
  postgresqldb:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1234  
      - POSTGRES_DB=postgres  